intelligentnode/IntelliNode

IntelliNode/config.json, IntelliNode/controller/RemoteImageModel.js, IntelliNode/model/input/ImageModelInput.js, IntelliNode/test/RemoteImageModel.test.js, IntelliNode/test_scripts.txt, IntelliNode/wrappers/StabilityAIWrapper.js
Add support to stable diffusion image model
=> support stable diffusion api

IntelliNode/README.md, IntelliNode/package.json, README.md, samples/command_sample/package-lock.json, samples/command_sample/package.json, samples/command_sample/test_image_models.js, samples/command_sample/test_language_models.js, samples/command_sample/test_speech_models.js
add samples and access instructions.
=> Create access samples

IntelliNode/README.md, IntelliNode/index.js, IntelliNode/package.json, README.md, samples/command_sample/package-lock.json, samples/command_sample/package.json, samples/command_sample/test_chatbot.js
add the chatbot access details
=> add chatbot support to the published module

IntelliNode/README.md, IntelliNode/function/Gen.js, IntelliNode/index.js, IntelliNode/package.json, IntelliNode/test/Gen.test.js
add easy to use business functions.
=> add Gen function

IntelliNode/function/Gen.js, IntelliNode/index.js, IntelliNode/package.json
=> Gen function

IntelliNode/README.md, IntelliNode/config.json, IntelliNode/controller/RemoteImageModel.js, IntelliNode/controller/RemoteLanguageModel.js, IntelliNode/function/Gen.js, IntelliNode/model/input/ImageModelInput.js, IntelliNode/model/input/LanguageModelInput.js, IntelliNode/package.json, IntelliNode/test/AzureOpenAIWrapper.test.js, IntelliNode/test/CustomGen.test.js, IntelliNode/test/OpenAIWrapper.test.js, IntelliNode/test/StabilityAIWrapper.test.js, IntelliNode/utils/ProxyHelper.js, IntelliNode/wrappers/OpenAIWrapper.js, IntelliNode/wrappers/StabilityAIWrapper.js
- Improve the Gen function to support backend engines.
- Add support to Openai Azure service.
- Add support to Openai proxy service.
=> Improvment 001

IntelliNode/function/Gen.js, IntelliNode/resource/templates/instruct_update.in, IntelliNode/test/Gen.test.js, IntelliNode/utils/SystemHelper.js
- add a function to update the model output based on users instructions.
- minor refinements to the Gen function like parameter names and token sizes.
=> Instruct gen function

IntelliNode/README.md, IntelliNode/function/Chatbot.js, IntelliNode/index.js, IntelliNode/model/input/ChatModelInput.js, IntelliNode/model/input/FunctionModelInput.js, IntelliNode/package.json, IntelliNode/test/integration/Chatbot.test.js, IntelliNode/test/unit/OpenAIWrapper.test.js, IntelliNode/test/unit/testRunner.js, IntelliNode/utils/Config2.js, IntelliNode/utils/ProxyHelper.js, IntelliNode/wrappers/OpenAIWrapper.js, samples/command_sample/README.md, samples/command_sample/automate_s3_bucket.js, samples/command_sample/package-lock.json, samples/command_sample/package.json
- update openai wrapper to support the organization key.
- update the chatbot to support functions call.
=> Openai upgrade

IntelliNode/README.md, IntelliNode/config.json, IntelliNode/function/Chatbot.js, IntelliNode/index.js, IntelliNode/model/input/ChatModelInput.js, IntelliNode/package.json, IntelliNode/test/integration/Chatbot.test.js, IntelliNode/test/integration/LLamav2.test.js, IntelliNode/wrappers/ReplicateWrapper.js, samples/command_sample/README.md, samples/command_sample/package-lock.json, samples/command_sample/package.json, samples/command_sample/test_llama_chatbot.js
- Add llama chat v2  support from replicate host.
- Update the chatbot to use llama as second option.
=> Add llama v2

IntelliNode/function/Gen.js, IntelliNode/index.js, IntelliNode/package.json, IntelliNode/utils/Prompt.js, IntelliNode/utils/SystemHelper.js, samples/command_sample/package-lock.json, samples/command_sample/package.json
Add prompt template feature.
Code example:
`new Prompt('text').format({key: value})`
=> Prompt manager

IntelliNode/README.md, IntelliNode/package.json, IntelliNode/resource/templates/prompt_example.in, IntelliNode/test/integration/Prompt.test.js, IntelliNode/utils/Prompt.js, IntelliNode/utils/SystemHelper.js, README.md
Add auto prompt feature to improve users prompts using LLMs.
=> Prompt engineering

README.md
add the prompt engineering example at the top
=> refine the readme code examples

IntelliNode/config.json, IntelliNode/function/Chatbot.js, IntelliNode/model/input/ChatModelInput.js, IntelliNode/package.json, IntelliNode/test/integration/LLamav2.test.js, IntelliNode/test/integration/ModelEvaluation.test.js, IntelliNode/utils/LLMEvaluation.js, IntelliNode/wrappers/ReplicateWrapper.js
Update the model evaluation to support llama v2
=> Multi model evaluation feature

IntelliNode/README.md, IntelliNode/config.json, IntelliNode/function/SemanticSearch.js, IntelliNode/function/SemanticSearchPaging.js, IntelliNode/index.js, IntelliNode/model/input/ChatModelInput.js, IntelliNode/package.json, IntelliNode/test/integration/Chatbot.test.js, IntelliNode/test/integration/LLamav2.test.js, IntelliNode/test/integration/SemanticSearchPaging.test.js, IntelliNode/wrappers/ReplicateWrapper.js, samples/command_sample/README.md, samples/command_sample/package-lock.json, samples/command_sample/test_llama_chatbot.js, samples/command_sample/test_semantic_search.js, samples/command_sample/test_semantic_search_pagination.js
- add support for llama-code and llama-python.
- upgrade the semantic search to support huge data memory search using `SemanticSearchPaging`.
- update the documentation.
=> Candidate 1.3.7

IntelliNode/README.md, IntelliNode/function/Chatbot.js, IntelliNode/index.js, IntelliNode/package.json, IntelliNode/test/integration/Chatbot.test.js, IntelliNode/test/integration/OpenAIWrapper.test.js, IntelliNode/utils/StreamParser.js, IntelliNode/wrappers/OpenAIWrapper.js, samples/command_sample/package-lock.json, samples/command_sample/package.json, samples/command_sample/test_chatbot.js
- update chatGPT to support streaming.
- update the chatbot with stream function.
- add test cases.
=> Add streaming functionality to the chatbot

IntelliNode/index.js, IntelliNode/test/integration/ChatContext.test.js, IntelliNode/utils/ChatContext.js
- Add an object to return the relevant chat messages from user input.
- Test the function and ensure working as expected.
=> add chat context functionality

IntelliNode/README.md, IntelliNode/package.json, samples/command_sample/package-lock.json, samples/command_sample/package.json, samples/command_sample/test_chat_context.js
=> Upgrade npm release

IntelliNode/index.js, IntelliNode/package.json
edit the ChatContext export declaration.
=> fix the index constant

IntelliNode/README.md, IntelliNode/config.json, IntelliNode/package.json, IntelliNode/test/integration/LLamav2.test.js
- Upgrade replicate llama models to the latest version.
- Increase the npm version.
=> Upgrade llama

IntelliNode/index.js, IntelliNode/package.json, package-lock.json
export cohere input to use it with the chatbot
=> add cohere input

IntelliNode/controller/RemoteEmbedModel.js, IntelliNode/package-lock.json, IntelliNode/package.json
Unify the embedding layer for cohere and replicate.
=> Unify embedding

IntelliNode/test/integration/OpenAIWrapper.test.js, IntelliNode/wrappers/OpenAIWrapper.js
Closes #69 - Vision model image to text with test case
- Added test case for vision AI testing
=> Closes #69 - Vision model image to text with test case

IntelliNode/model/input/ImageModelInput.js, IntelliNode/test/integration/RemoteImageModel.test.js
=> Closes #69 - Dall-e-3 update

IntelliNode/config.json, IntelliNode/controller/RemoteSpeechModel.js, IntelliNode/model/input/Text2SpeechInput.js, IntelliNode/test/integration/OpenAIWrapper.test.js, IntelliNode/test/integration/RemoteSpeechModel.test.js, IntelliNode/utils/ProxyHelper.js, IntelliNode/wrappers/OpenAIWrapper.js
=> Closes #69 - Text to speech

IntelliNode/README.md, IntelliNode/package.json
=> adjust the version

IntelliNode/config.json, IntelliNode/function/Chatbot.js, IntelliNode/index.js, IntelliNode/model/input/ChatModelInput.js, IntelliNode/package-lock.json, IntelliNode/package.json, IntelliNode/resource/templates/augmented_chatbot.in, IntelliNode/test/integration/ChatbotWithData.test.js, IntelliNode/test/integration/intellicloudWrapper.test.js, IntelliNode/utils/SystemHelper.js, IntelliNode/wrappers/IntellicloudWrapper.js, IntelliNode/wrappers/OpenAIWrapper.js
Add supported to augment chatbot that provide answers from the user documents.
=> 82 add support for intellinode data loader

IntelliNode/README.md, IntelliNode/package.json
=> update the publish details

IntelliNode/config.json, IntelliNode/controller/RemoteFineTune.js, IntelliNode/controller/RemoteSpeechModel.js, IntelliNode/model/input/FineTuneInput.js, IntelliNode/test/integration/OpenAIWrapper.test.js, IntelliNode/test/integration/RemoteFineTune.test.js, IntelliNode/test/integration/RemoteSpeechModel.test.js, IntelliNode/utils/ProxyHelper.js, IntelliNode/wrappers/OpenAIWrapper.js
=> Closes #15

IntelliNode/README.md, IntelliNode/config.json, IntelliNode/controller/RemoteFineTune.js, IntelliNode/function/Gen.js, IntelliNode/index.js, IntelliNode/package.json, IntelliNode/test/integration/AzureOpenAIWrapper.test.js, IntelliNode/test/integration/Gen.test.js, IntelliNode/test/integration/RemoteFineTune.test.js, IntelliNode/utils/AudioHelper.js, IntelliNode/utils/Config2.js, IntelliNode/utils/FileHelper.js, IntelliNode/utils/Prompt.js, IntelliNode/utils/ProxyHelper.js, IntelliNode/utils/SystemHelper.js
- prepare intellinode to release fine tune activity.
- fix azure wrapper links.
=> Prepare fine tune release

IntelliNode/README.md, IntelliNode/model/input/ChatModelInput.js, IntelliNode/package.json, IntelliNode/test/integration/Chatbot.test.js, README.md
=> 81 add support for gemini model

IntelliNode/config.json, IntelliNode/controller/RemoteEmbedModel.js, IntelliNode/model/input/EmbedInput.js, IntelliNode/test/integration/CohereAIWrapper.test.js, IntelliNode/test/integration/GeminiAIWrapper.test.js, IntelliNode/test/integration/RemoteEmbedModel.test.js, IntelliNode/wrappers/GeminiAIWrapper.js
1. Updated `GeminiAIWrapper.js` to include embedding functions
2. Updated `GeminiAIWrapper.test.js` with extra unit test case for embedding 
3. Updated `RemoteEmbedModel.js` by adding Gemini as providing, calling the related function.
4. Updated `RemoteEmbedModel.test.js` to include an extra unit test case for the Gemini provider.
5. Updated `config.json` to include the Gemini embedding endpoint
---
With this PR, we should close issue #94 
Attached are two text files the results of the `GeminiAIWrapper.test.js` and `RemoteEmbedModel.test.js` test runs:
- [GeminiAIWrapperTestResults_20240112_212623.txt](https://github.com/intelligentnode/IntelliNode/files/13926495/GeminiAIWrapperTestResults_20240112_212623.txt)
- [RemoteEmbedModelTestsResults_20240112_221249.txt](https://github.com/intellig …
=> feat: Add embedding functions and unit tests for Gemini

IntelliNode/model/input/EmbedInput.js, IntelliNode/test/integration/OpenAIWrapper.test.js, IntelliNode/test/integration/RemoteEmbedModel.test.js
Updated openai `text-embedding-ada-002` to new model `text-embedding-3-small`
---
Attached is a text file with results of the `RemoteEmbedModel.test.js` using the new `text-embedding-3-small` model:
[RemoteEmbedModelTestsResults_20240126_134458.txt](https://github.com/intelligentnode/IntelliNode/files/14068283/RemoteEmbedModelTestsResults_20240126_134458.txt)
=> feat: update openai `text-embedding-ada-002` to new model `text-embedding-3-small`

IntelliNode/README.md, IntelliNode/function/Chatbot.js, IntelliNode/model/input/ChatModelInput.js, IntelliNode/package.json, IntelliNode/test/integration/ChatbotWithData.test.js, samples/command_sample/package-lock.json, samples/command_sample/package.json
Update the chatbot to return the referenced documents in the responses.
=> 101 add references to the chatbot

IntelliNode/README.md, IntelliNode/package.json
=> Update intellinode desc

IntelliNode/test/integration/intellicloudWrapper.test.js, IntelliNode/wrappers/IntellicloudWrapper.js
Add docuiment filter option to the semantic search, allowing to pick specific doc to apply the search. If empty, will apply to all docs.
=> add document name filter

IntelliNode/README.md, IntelliNode/package.json, README.md
- update community reference.
- adjust docs upload instructions.
=> update publish details

IntelliNode/README.md, IntelliNode/package.json
- update readme.
- update the npm description.
=> update release details

IntelliNode/README.md, IntelliNode/model/input/LanguageModelInput.js, IntelliNode/package.json, IntelliNode/test/integration/OpenAIWrapper.test.js, IntelliNode/test/integration/RemoteLanguageModel.test.js, README.md, samples/command_sample/ecommerce_tool.js, samples/command_sample/package-lock.json, samples/command_sample/package.json, samples/command_sample/test_language_models.js
- fix the openai complesion.
- add reference to the new doc website.
=> Fix deprecation and add docs

IntelliNode/README.md, IntelliNode/config.json, IntelliNode/function/Chatbot.js, IntelliNode/index.js, IntelliNode/model/input/ChatModelInput.js, IntelliNode/package.json, IntelliNode/test/integration/AnthropicWrapper.test.js, IntelliNode/test/integration/Chatbot.test.js, IntelliNode/test/integration/ModelEvaluation.test.js, IntelliNode/utils/LLMEvaluation.js, IntelliNode/wrappers/AnthropicWrapper.js
Add support for anthropic model.
=> 110 add anthropic model

IntelliNode/function/Gen.js, IntelliNode/package.json, IntelliNode/test/integration/Gen.test.js
Update the Gen function to receive custom parameters for the website and dashboard creation.
=> Release 1.8.7

.gitignore, IntelliNode/README.md, IntelliNode/config.json, IntelliNode/function/Chatbot.js, IntelliNode/index.js, IntelliNode/model/input/ChatModelInput.js, IntelliNode/package-lock.json, IntelliNode/package.json, IntelliNode/test/integration/ChatbotNvidia.test.js, IntelliNode/test/integration/NvidiaWrapper.test.js, IntelliNode/wrappers/NvidiaWrapper.js, samples/command_sample/package-lock.json, samples/command_sample/package.json, samples/command_sample/test_chatbot_nvidia.js
Add support for the latest models, including DeepSeek and Llama 3, via the NVIDIA stack.
=> 113 add nvidia api including deepseek

IntelliNode/README.md, IntelliNode/model/input/ChatModelInput.js, IntelliNode/package-lock.json, IntelliNode/package.json, IntelliNode/test/integration/ModelEvaluation.test.js, IntelliNode/test/integration/OpenAIWrapper.test.js, IntelliNode/test/integration/RemoteFineTune.test.js, IntelliNode/test/integration/RemoteLanguageModel.test.js, README.md
Change the default openai version to GPT4o
=> Update default openai

IntelliNode/model/input/ChatModelInput.js, IntelliNode/package-lock.json, IntelliNode/package.json, IntelliNode/test/integration/ChatbotCohere.test.js, samples/command_sample/package-lock.json, samples/command_sample/package.json, samples/command_sample/test_chatbot.js, samples/command_sample/test_chatbot_cohere.js
- Improve description.
- Fix issue with cohere multiple messages.
- Add latest cohere and openai models as default.
=> Fix edge cases

IntelliNode/package-lock.json, IntelliNode/package.json, IntelliNode/test/integration/Chatbot.test.js, IntelliNode/utils/StreamParser.js, samples/command_sample/package-lock.json, samples/command_sample/package.json, samples/command_sample/test_chatbot.js
- Fix openai streaming issue which used to cut part of the text.
- Add test cases to confirm the fix.
=> Fix the streaming issue

IntelliNode/README.md, IntelliNode/package-lock.json, IntelliNode/package.json, IntelliNode/test/integration/Chatbot.test.js, IntelliNode/utils/ConnHelper.js, IntelliNode/utils/FetchClient.js, IntelliNode/wrappers/AWSEndpointWrapper.js, IntelliNode/wrappers/AnthropicWrapper.js, IntelliNode/wrappers/CohereAIWrapper.js, IntelliNode/wrappers/GeminiAIWrapper.js, IntelliNode/wrappers/GoogleAIWrapper.js, IntelliNode/wrappers/HuggingWrapper.js, IntelliNode/wrappers/IntellicloudWrapper.js, IntelliNode/wrappers/MistralAIWrapper.js, IntelliNode/wrappers/NvidiaWrapper.js, IntelliNode/wrappers/OpenAIWrapper.js, IntelliNode/wrappers/ReplicateWrapper.js, IntelliNode/wrappers/StabilityAIWrapper.js, README.md
**Changes**
- Remove axios as a dependency.
- Implement fetch-based requests in all wrapper modules.
=> replace axios with native fetch

IntelliNode/function/Chatbot.js, IntelliNode/package-lock.json, IntelliNode/package.json
Adjust vLLM to set the reference data.
=> Add reference to vLLM models
